---
- name: Check Apache Status and Create HTML Page
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Collect service facts
      ansible.builtin.service_facts:

    - name: Set Apache status fact
      ansible.builtin.set_fact:
        apache_status: >-
          {% if 'httpd' in services %}
            {{ 'running' if services['httpd'].state == 'running' else 'stopped' }}
          {% elif 'apache2' in services %}
            {{ 'running' if services['apache2'].state == 'running' else 'stopped' }}
          {% else %}
            not installed
          {% endif %}

    - name: Generate HTML page with Apache status and Hostname
      ansible.builtin.template:
        src: templates/status.html.j2
        dest: /tmp/status.html
        owner: root
        group: root
        mode: '0644'
